# Generated by Django 2.0.8 on 2019-01-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffxivbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('nickname', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate', models.TextField(default='[]')),
            ],
        ),
        migrations.AddField(
            model_name='qqbot',
            name='command_stat',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='qqbot',
            name='img_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qqbot',
            name='long_query_interval',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='qqbot',
            name='share_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qqgroup',
            name='group_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='weibotile',
            name='itemid',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='territory',
            name='weather_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ffxivbot.WeatherRate'),
        ),
    ]
